CL: Create Page for UCSBOrganization plus tests and stories
ucsb-cs156-f24/proj-rec-f24-06 pull request #81
Opened 2024-11-24 01:28 UTC by chriswlai

2024-11-25 08:59 UTC, vprchlik submitted a review, later dismissed
LGTM

2024-11-27 01:23 UTC, skanda-vasishta approved these changes
LGTM!

2024-11-29 19:52 UTC, pconrad requested changes
Commented out code, and a poor user experience for the error that comes up when duplicate RequestTypes are entered.

Here's the fix for the error message: 

https://github.com/ucsb-cs156-f24/proj-courses-f24-02/blob/d7ee97a74cc8f99ced08b81f6be1742b9cf9a09d/frontend/src/main/pages/PersonalSchedules/PersonalSchedulesCreatePage.js#L20

The code looks like this (though you'll need to adapt it to your situation; you can't just copy paste this):

```jsx
  const onError = (error) => {
    toast(`Error: ${error.response.data.message}`);
  };

  const mutation = useBackendMutation(
    objectToAxiosParams,
    { onSuccess, onError },
    // Stryker disable next-line all : hard to set up test for caching
    ["/api/personalschedules/all"],
  );
```

The backend is already producing a reasonable error message:

```
  "message": "Request Type with this description already exists"
```

We just need to show that to the end user instead of the generic one.

2024-11-29 19:52 UTC, pconrad commented on frontend/src/main/components/RequestType/RequestTypeForm.js
> +      {/* <Form.Group className="mb-3">
What is "commented out code" doing in a PR that's marked "Ready For Staff"?

And why did both the original PR author and the person that did the code review think this was ok?

It's literally the first thing in the list of PR Criteria.

https://ucsb-cs156.github.io/topics/pull_requests/#pr-checklist

It's kind of astonishing to still see that at this stage.

2024-12-03 16:45 UTC, pconrad commented
Closing per slack channel conversation: https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/81

2024-12-03 16:45 UTC, closed without merging